apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-crawler
spec:
  schedule: "*/5 * * * *"  # Programa para que se ejecute cada hora
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: s3-crawler-container  # Nombre en minúsculas, válido según RFC 1123
            image: {{ .Values.config.docker_registry }}/{{ .Values.config.producer.image }}
            env:
              - name: S3_KEY_PREFIX       # Esto está bien como variable de entorno
                value: "spotify/"
              - name: S3_BUCKET           # Variable de entorno válida
                value: "2024-02-ic4302-gr1"
              - name: AWS_ACCESS_KEY_ID   # Variable de entorno válida
                value: "AKIAQ2VOGXQDTWAX4PUY"
              - name: AWS_SECRET_ACCESS_KEY # Variable de entorno válida
                value: "Ks9UU/Ll1sWNP+YQgmeciXoTRyT0f5frRWzzOkLE"
              - name: RABBITMQ            # Variable de entorno válida
                value: "databases-rabbitmq"
              - name: RABBITMQ_QUEUE      # Variable de entorno válida
                value: "queue"
              - name: RABBITMQ_USER       # Variable de entorno válida
                value: "user"
              - name: RABBITMQ_PASS       # Usando secretKeyRef para la contraseña
                valueFrom:
                  secretKeyRef:
                    name: databases-rabbitmq
                    key: rabbitmq-password
                    optional: false
          restartPolicy: OnFailure
