{
 "title": "Memcached",
 "description": "Visualize memcached-exporter metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(memcached_up, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Instance uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_uptime_seconds{job=\"$job\"} and memcached_up{job=\"$job\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_uptime_seconds{job=\"$job\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (pod) (memcached_current_bytes{job=\"$job\"}/memcached_limit_bytes{job=\"$job\"})",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Hit & Miss ratio",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum (rate(memcached_commands_total{job=\"$job\", command=\"get\", status=\"hit\"}[1m]))\n/ sum (rate(memcached_commands_total{job=\"$job\", command=\"get\"}[1m]))",
     "legendFormat": "hit"
    },
    {
     "expr": "  sum (rate(memcached_commands_total{job=\"$job\", command=\"get\", status=\"miss\"}[1m]))\n/ sum (rate(memcached_commands_total{job=\"$job\", command=\"get\"}[1m]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Get & Set ratio",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{command=\"get\",job=\"$job\"}[1m]))\n/ \nsum(rate(memcached_commands_total{command=~\"get|set\",job=\"$job\"}[1m]))",
     "legendFormat": "get"
    },
    {
     "expr": "sum(rate(memcached_commands_total{command=\"set\",job=\"$job\"}[1m]))\n/\nsum(rate(memcached_commands_total{command=~\"get|set\",job=\"$job\"}[1m]))",
     "legendFormat": "set"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Items",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memcached_current_items{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Evicts (total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_items_evicted_total{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Reclaims (total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memcached_items_reclaimed_total{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Accepting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_accepting_connections{job=\"$job\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Throttled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memcached_connections_yielded_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Refused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memcached_connections_listener_disabled_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Too large",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memcached_item_too_large_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "No Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memcached_item_no_memory_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "any(memcached_version{job=\"$job\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "memcached_current_connections{job=\"$job\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "memcached_current_connections{job=\"$job\"} / memcached_max_connections{job=\"$job\"}",
     "legendFormat": "% {{pod}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{job=\"$job\"}[$__rate_interval]))/30",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Get Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{status=\"hit\",command=\"get\",job=\"$job\"}[$__rate_interval]))\n/\nsum(rate(memcached_commands_total{command=\"get\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(memcached_read_bytes_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "read {{ pod }}"
    },
    {
     "expr": "- sum by (pod) (rate(memcached_written_bytes_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "write {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memcached_current_bytes{job=\"$job\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "memcached_current_bytes{job=\"$job\"}\n/\nmemcached_limit_bytes{job=\"$job\"}",
     "legendFormat": "%{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(memcached_process_system_cpu_seconds_total{job=\"$job\"}[$__rate_interval]) + rate(memcached_process_user_cpu_seconds_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Evicts & Reclaims rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_items_evicted_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "evicts"
    },
    {
     "expr": "sum(rate(memcached_items_reclaimed_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "New Items",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(memcached_items_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "memcached_current_items{job=\"$job\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{job=\"$job\"}[$__rate_interval])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{job=\"$job\", status=\"hit\"}[1m]))\n/\nsum(rate(memcached_commands_total{job=\"$job\"}[1m]))",
     "legendFormat": "Total Hit Ratio"
    },
    {
     "expr": "sum(rate(memcached_commands_total{status=\"hit\",command=\"get\",job=\"$job\"}[$__rate_interval]))\n/\nsum(rate(memcached_commands_total{command=\"get\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Get Hit Ratio"
    }
   ]
  },
  {
   "title": "Hit Ratio Per Command",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum by (command) (rate(memcached_commands_total{job=\"$job\", status=\"hit\"}[1m]))\n/ sum by (command) (rate(memcached_commands_total{job=\"$job\"}[1m])) ",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}