mariadb:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"

elastic:
  enabled: true
  version: 8.6.1
  replicas: 1
  name: ic4302

kibana:
  version: 8.6.1
  replicas: 1
  name: ic4302

prometheus-elasticsearch-exporter:
  es:
    uri: http://ic4302-es-http:9200
    cluster_settings: true
  serviceMonitor:
    enabled: true
    namespace: monitoring

memcached:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"

rabbitmq:
  enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"