apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: huggingfaceapi-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: huggingfaceapi
  endpoints:
    - port: metrics
      interval: 10s