from os import getenv

MONGO_URI = getenv("MONGO_URI")
MONGO_DB = getenv("MONGO_DB")

POSTGRES = getenv("POSTGRES")
POSTGRES_DB = getenv("POSTGRES_DB")
POSTGRES_USER = getenv("POSTGRES_USER")
POSTGRES_PASSWORD = getenv("POSTGRES_PASSWORD")

ELASTIC = getenv("ELASTIC")
ELASTIC_USER = getenv("ELASTIC_USER")
ELASTIC_PASSWORD = getenv("ELASTIC_PASSWORD")
ELASTIC_INDEX_NAME = getenv("ELASTIC_INDEX_NAME")