config:
  docker_registry: tonybarr16

  access_key: AKIAQ2VOGXQDTWAX4PUY
  secret_key: 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
  bucket: 2024-02-ic4302-gr1
  producer:
    replicas: 0
    name: s3-crawler
    image: s3-crawler
  consumer:
    replicas: 1
    name: ingest
    image: ingest
  huggingfaceApi:
    name: huggingfaceapi
    replicas: 1
    image: huggingface-api
