apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2
---
apiVersion: v1 
kind: ConfigMap
metadata:
  name: scala
data:
{{ (.Files.Glob "scala/app.scala").AsConfig | indent 2 }}