config:
  docker_registry: mwgh
  type: service_account
  project_id: formal-incline-431300-v8
  private_key_id: b810b4ffbab660f24f04834af2294a4283f70c91
  private_key: -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDVchjltigDOKJP\nuo/X9DULaCJvG+Lvfrj9hzR9Zx+haIFj0P+8eU1hWn15WLQhztMSEnKAaSBLiXKl\ngE+EdPQHhD9ncV41cIH3W1PfI1mmCrUVytsNWUmmy7v1HNTrKJD7oyq24OEW7GQO\nqW8VMr706AVi3xr1wEGZJ2VahSD29h539bkOm6Qh7u1LQ6oJeiK7uJS2j57FpwFP\nf3uPqU5inv+jB3GZ5mqVNyJKBPC5scRLE7rcnJiPAGBvKZ7W/bxTM/QYTVXdi/nt\nZ5qjwtGlqCvO6b/MnDfB2D80PT+4IGWBbVpySQ3ZmHKDdWjupbg+yJuLSNbYDTvZ\nQ87eAbuJAgMBAAECggEAHJL9NUdY/PFofT7vAcyOC1xh+7jifQhccIhYpQ8Yo22P\noNK6Ybtlegp4sLWIy9vZ0toIXRt1uNcKM5DFVGipwJXaPRlmsMXCiGBADqe3WSym\nyGeTQqq42uz8WRiGgoK4Qg+6aKgbSgvUa0gQeGiGOtgS3IUcoVifD4dAIMmgu57B\npl2joFUPgAeoWo4FodgKJVsl41cBkJWL9bXpsswyeH7vu3X3hDZE5xsjaLK8Rk0A\nwZ5tBAJzzLIUNwpQ/f6B8rgX0iRVKVpoaHRxbEIkYDr6YbYeNirPPEvGJskjAWQe\ncOsvtZFRiuW4GEBAcaFqdEq/CzgS/QsqrLwkDf5+lwKBgQDtNGGMVLVTJYwwGkrl\nj8tJIsLkXYtohIGv8ilpbmmhUnEBeAIlw80mc9tul9oEL5yg4or9r3piMKYYMJxb\nwFsK/n4vKuQsAbKomO24e4GxfIAytMSVkVRpcsVJ0aqOnO4tn2spy8G2Rpz3QSVa\nu8ILIFjMcsFRzPUmUh1741SbowKBgQDmW8Yv90HXKW7he8ZxdzKi4DDt4thyUPyR\ngbJZ8oHjseBmWpdDg+EQgInGWJHtBRAh6qqJ5YAscYbTgtvAhNgBBq9OE0uCTw8s\nkZhsLntvfKuJcaq7qjP3mAGRy8/86XFWPgUl4EmJyNa3aXXlB+1+D+Kh2uo5twLK\ns6rUwzD+4wKBgGTJKuF7ZIftnkEaCtS7Yj6y/GgXrxI7qvbdR+c6OLuI0ecz3IW7\nSkGaXJQDBWld6YkaeMANfUyXKxuAHA+IDacANxFHgieImSa1w9vs7lBBfB8PW6/J\nTjp3v4f8BCIQX8sWv2vE3YvbOPp9vadtu6cKmXBVGfrtwQQFQ+3Ny7dNAoGASzWJ\ndl2e5HXFmt7DgoYtRRo3P2PB0Uj5vTQAG/feSo3nuuM24bcsAyxETzrZoe32P2yT\nc2Q3vcru/x2JS8jTkToygCYyj//p7141ypQ+fr7QbpZq7Mx8HQlG8ef+Jw+8jjC/\nk4cv20l0OPu4nydAddkP4FJOCLvksHOKgd6cn4sCgYEApsG49eT8EqYpIJDC+eDX\nqOCRD+ozTDGlJ8gs9G8ScquiG3Uil2TxWJGt4+Rr8EayYNsKZnJtWmju+HrUaV4X\nLOx73mXjNEI871U/7FN+W8LNDxiMugZrUXjd6iiWNXN07GaF20BHZBE3iVUzdCqZ\nQIocb3YffnceUXtQwR2L3VE=\n-----END PRIVATE KEY-----\n
  client_email: ic4302-202402@formal-incline-431300-v8.iam.gserviceaccount.com
  client_id: 110637389271419754928
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/ic4302-202402%40formal-incline-431300-v8.iam.gserviceaccount.com
  universe_domain: googleapis.co
  loader:
    replicas: 1
    name: loader
    image: loader
  migrator:
    replicas: 1
    name: migrator
    image: migrator