apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.backendapi.name }}-service
  namespace: default
  labels:
    app: {{ .Values.config.backendapi.name }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '5000'
    prometheus.io/path: '/metrics'
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.config.backendapinodeport.port }}
      targetPort: {{ .Values.config.backendapinodeport.targetPort }}
      nodePort: {{ .Values.config.backendapinodeport.nodePort }}
  selector:
    app: {{ .Values.config.backendapi.name }}
  type: NodePort
