apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.backendapi.name }}-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.config.backendapinodeport.port }}
      targetPort: {{ .Values.config.backendapinodeport.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.config.backendapinodeport.nodePort }}
  selector:
    app: {{ .Values.config.backendapi.name }}
