{
 "title": "HuggingFace",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Amount",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "request_amount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Embedding Generation Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(embedding_generation_time_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Embedding Generation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(embedding_generation_time_seconds_sum[5m]) / rate(embedding_generation_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Embedding Generation Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0, min(embedding_generation_time_seconds_bucket))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}