{
 "title": "Ingest Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Processed Objects by Ingest",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Objects" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "objects_processed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Processed Rows by Ingest",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Rows" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rows_processed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Rows with Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Rows" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rows_error", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Object Processing Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(object_processing_time_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Object Processing Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0, min(object_processing_time_seconds_bucket))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Row Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "rate(row_processing_time_seconds_sum[5m]) / rate(row_processing_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Row Processing Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(row_processing_time_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Row Processing Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0, min(row_processing_time_seconds_bucket))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Object Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "rate(object_processing_time_seconds_sum[5m]) / rate(object_processing_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}