{{ if .Values.config.loader.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.loader.name }}
  labels:
    app: {{ .Values.config.loader.name }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.config.loader.name }}
    spec:
      containers:
      - name: {{ .Values.config.loader.name }}
        image: {{ .Values.config.loader.image }}
        env:
        - name: POSTGRES
          value: "databases-postgresql"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databases-postgresql
              key: postgres-password
              optional: false
        - name: MARIADB
          value: "databases-mariadb"
        - name: MARIADB_USER
          value: "root"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databases-mariadb
              key: mariadb-root-password
              optional: false
        - name: ELASTIC_USER
          value: "elastic"
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ic4302-es-elastic-user
              key: elastic
              optional: false
        - name: ELASTIC
          value: "http://ic4302-es-http:9200"
      restartPolicy: Never
{{ end }}
